### ISSUE TITLE
Support HTTP/1.1

### ISSUE THREAD

**Issue by Lukasa** [kespindler/albatross#1]
Right now the server claims to send HTTP/1.0 responses. This is pretty sad, given that HTTP/1.1 was specced in 1999 (that is, it's nearly old enough to vote!).

You should consider doing one of the following three things:
1. Updating your server to support HTTP/1.1 as specced in RFC 7230, RFC 7231, and RFC 7232.
2. Using [h11](https://github.com/njsmith/h11) to build your server, giving you easy and correct HTTP/1.1 support.
3. Using an already written asyncio HTTP server.

**Comment by kespindler** [comment]
Thanks for this excellent feedback Lukasa. I'll move over to h11 next weekend !

**Comment by kespindler** [comment]
Have you also seen https://github.com/MagicStack/httptools ? Would be sweet to have a benchmark comparing the two.

**Comment by Lukasa** [comment]
I'd be surprised in h11 came anywhere near the performance of httptools, at least in CPython. Using either will work just fine. =)

**Comment by kespindler** [comment]
Using httptools for parsing as of albatross>=0.5.0. You still clearly know way more about HTTP than I do, so welcome any more bug reports :) Thanks for your help here.
