### ISSUE TITLE
Persistent database connection

### ISSUE THREAD

**Issue by yohanboniface** [kespindler/albatross#14]
Playing around with albatross, I don't see a way to have an async persistent database connection.
It may just be me missing something :)

Here is an example with aiohttp: https://magicstack.github.io/asyncpg/current/examples.html

Thanks for your lights!

**Comment by kespindler** [comment]
I'm trying to keep albatross lean. I've been meaning to add an example of how to integrate with database. It's pretty simple. In a nutshell, in the `Server.initialize` function, you want to init the database pool and attach it to your server instance. Then you can import the server instance wherever you need db connectivity, and use its pool.

In my projects, I inject the engine as a property to all my controller classes within that same initialize function.

**Comment by yohanboniface** [comment]
Thanks, makes sense :)

**Comment by yohanboniface** [comment]
(But circular imports may be around the corner ;) )
