### ISSUE TITLE
Prevent pylint from complaining `res` does not exist

### ISSUE THREAD

**Issue by kootenpv** [kespindler/albatross#6]
On the example:

```
class Handler:
    async def on_get(self, req, res):
        print("serving")
        res.write('Hello {}'.format(req.args['name']))

```

we get pylint to complain:

```
[ERROR] Undefined variable 'res' (undefined-variable) 
```

Is there something that can be done about it (without having to resort to shutting up pylint)?

**Comment by kespindler** [comment]
Any thought why? It's an arg to that function..

**Comment by kootenpv** [comment]
I'm sorry, I do not know the internals, hopefully it's obvious for others.

**Comment by kespindler** [comment]
Is it possible you ran with a version of pylint with python2? What is exact command you used?

I just did `pylint examples/basic.py`. (While I got some other warnings), I didn't get the undefined variable res error that you did.

**Comment by kootenpv** [comment]
Yea, I think I have to specifically have the editor use "pylint --py3k" perhaps? This is the result of my editor. But it does not choke on `print 1`. So I don't know what is going on.

pascal@MBP:~ $ pylint --version
pylint 1.5.0,
astroid 1.4.0
Python 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

pascal@MBP:~ $ pylint server.py
************* Module server
C:  1, 0: Missing module docstring (missing-docstring)
C:  5, 0: Missing class docstring (missing-docstring)
E:  8, 8: Undefined variable 'res' (undefined-variable)
E:  8,36: Undefined variable 'req' (undefined-variable)
R:  5, 0: Too few public methods (1/2) (too-few-public-methods)
C: 11, 0: Invalid constant name "app" (invalid-name)

**Comment by kootenpv** [comment]
Old version of pylint... should have known :/ My apologies for having this added as an issue.
